title: My Personal Wiki
theme: minima
navigation:
  - title: Home
    url: /
  - title: Computer Science
    url: /computer science/
    subcategories:
      - title: Program Language
        url: /computer science/program-language/
      - title: Data Science
        url: /comupter science/data-science/
      - title: Software Engineering
        url: /computer science/software-engineering/