title: My Personal Wiki
theme: minima
navigation:
  - title: Home
    url: /
  - title: Computer Science
    url: /computer_science/
  - title: Power Electronics
    url: /power_electronics/
    #subcategories:
     # - title: Program Language
      #  url: /computer_science/program-language/
      #- title: Data Science
      #  url: /comupter_science/data-science/
      #- title: Software Engineering
      #  url: /computer_science/software-engineering/